# Generated by Django 4.2.5 on 2023-10-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
