# Generated by Django 4.2.6 on 2023-10-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prooduct',
            new_name='product',
        ),
    ]
