# Generated by Django 4.2.5 on 2023-10-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost',
        ),
    ]
