# Generated by Django 4.2.5 on 2023-10-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_discount_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.FloatField(default=0),
        ),
    ]
