# Generated by Django 4.2.5 on 2023-10-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_grand_total_order_shipping_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_amount',
            new_name='shipping_cost',
        ),
    ]
