# Generated by Django 4.2.5 on 2023-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_status_code_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='processing', max_length=50),
        ),
    ]
